library(data.table)
full_dt <- fread("household_power_consumption.txt", na.strings=c("?", "NA"))
dt <- subset(full_dt, subset=(Date=='1/2/2007'|Date=='2/2/2007'))
dt$Global_active_power <- as.numeric(dt$Global_active_power)
dt$Date <- as.Date(dt$Date, format='%d/%m/%Y')
times <- strptime(paste(dt$Date, dt$Time), format="%Y-%m-%d %H:%M:%S")
png(filename="plot3.png", width=504, height=504)
plot(times, dt$Sub_metering_1, xlab="", ylab="Energy sub metering", type="l")
lines(times, dt$Sub_metering_2, col="red")
lines(times, dt$Sub_metering_3, col="blue")
legend("topright", lty=1, col=c("black", "red", "blue"),
       legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
